export type TitleMapKey =
  | 'mypage'
  | 'profile'
  | 'editstyle'
  | 'editbodyinfo'
  | 'editsize'
  | 'reqlist'
  | 'newreq'
  | 'editrequest'
  | 'paymentlist'
  | 'charge'
  | 'likelist'
  | 'followlist'
